@url=http://localhost:3000
@id=2l0GeY0SUimhvWuARjeLYiWHHSC
###
GET {{url}}/api/books HTTP/1.1
Content-Type: application/json

###
GET {{url}}/api/books/{{id}} HTTP/1.1
Content-Type: application/json

###
POST {{url}}/api/books HTTP/1.1
Content-Type: application/json

{
  "name": "The Great Escape"
}

###
PUT {{url}}/api/books/{{id}} HTTP/1.1
Content-Type: application/json

{
  "name": "Hello World!"
}

###
DELETE {{url}}/api/books/{{id}} HTTP/1.1
Content-Type: application/json


